name: Main

on:
  push:
    branches: [ master ]

jobs:
  build-archive:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Package with Maven
        run: mvn package
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PercentCalculator
          path: ./percent-calculator-service/target/PercentCalculator.jar
          retention-days: 1
  deploy:
    needs: build-archive
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: PercentCalculator
          path: ./PercentCalculator
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Upload
        run: rsync -crlOt ./PercentCalculator/PercentCalculator.jar ubuntu@3.123.232.27:/home/ubuntu/PercentCalculator.jar
      - name: Restart
        run: ubuntu@3.123.232.27 service percent-calculator restart